FROM node:18-alpine AS build
WORKDIR /app
COPY ./Frontend/inventario-app/ .
RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/inventario-app/browser /usr/share/nginx/html
COPY ./Frontend/inventario-app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]